### PR TITLE
Post review edits

### PR DESCRIPTION
**Pull request by oganm**
https://github.com/Bioconductor/Contributions/issues/2533#issuecomment-1165016893

Hi @yavyx and @oganm,

Thank you for submitting **gemma.R** to Bioconductor. The **gemma** service looks interesting and it will be good to have an R interface to it that can return standard Bioconductor objects such as _SummarizedExperiment_ or _ExpressionSet_ objects.

The package is largely in good shape. I do still have concerns with the caching system you have implemented, but I think these can be addressed. For acceptance into Bioconductor, there are a number of Required points, as well as Recommended points, that I would ask you to first please address. Would you please provide line-by-line comments to my initial review so that I know what changes I'm looking for in my re-review.

Cheers, Pete

### Required
* [x]  The default cache location is `rappdirs::user_cache_dir(appname = "gemmaR")` (as set by `gemma.R:::gemmaCache()`) but is documented in the vignette as being `tools::R_user_dir("gemmaR", which = "cache")`. Please reconcile.

> Vignette is fixed accordingly

```r
rappdirs::user_cache_dir(appname = "gemmaR")
#> [1] "~/Library/Caches/gemmaR"
tools::R_user_dir("gemmaR", which = "cache")
#> [1] "/Users/Peter/Library/Caches/org.R-project.R/R/gemmaR"
```

* [x]  The value of `getOption("gemma.cache")` is not respected by the caching functionality. I.e. if a user sets this to a non-default location then it is silently ignored; see reprex below.

> Using non-default cache locations used to require reloading of the package as stated in documentation. This behaviour is now changed so that reloading the package is no longer necessary. Documentation is changed accordingly

```r
# getOption("gemma.cache") is not respected

library(gemma.R)
forgetGemmaMemoised()
#> [1] TRUE

# Set path to the cache (as advised in vignette).
cache_path <- tools::R_user_dir("gemmaR", which = "cache")
options(gemma.cache = cache_path)
getOption("gemma.cache")
#> [1] "/Users/Peter/Library/Caches/org.R-project.R/R/gemmaR"
list.files(getOption("gemma.cache"))
#> character(0)

# Download data and cache it
dat <- getDataset("GSE46416", memoised = TRUE)

# Files don't appear in my cache
list.files(cache_path)
#> character(0)
# But instead appear here
list.files(rappdirs::user_cache_dir(appname = "gemmaR"))
#> [1] "8cf8e3c0440797a3" "b9ef0ae235fd3194" "f4cad949517a257c"
```

* [x]  It appears data are only loaded from the cache if `memoised = TRUE` in the subsequent function calls (see reprex below). The documentation reads like `memoised = TRUE` is only required on the first use to cache the data and that any subsequent calls to load the same data will make use of the cache whether `memoised = FALSE` or `memoised = TRUE`. I.e. I expected the cache to be automatically used if the data were already downloaded. It's not clear to me if this is an issue with the implementation or the documentation.

> Documentation is fixed to clarify the intended functionality. In function `memoised` argument's description is changed to "Whether or not to save to cache for future calls with the same inputs and use the result saved in cache if a result is already saved. Doing `options(gemma.memoise = TRUE)` will ensure you are always using the cache. Use `forgetGemmaMemoised` to clear the cache." Vignette is similarly clarified

```r
library(gemma.R)

# Cache isn't set on package load.
getOption("gemma.cache")
#> NULL

# Let's setup a cache directory.
cache_path <- rappdirs::user_cache_dir(appname = "gemmaR")
options(gemma.cache = cache_path)
getOption("gemma.cache")
#> [1] "~/Library/Caches/gemmaR"
list.files(cache_path)
#> character(0)

# Download data and cache it
system.time(dat <- getDataset("GSE46416", memoised = TRUE))
#>    user  system elapsed 
#>   7.255   0.634  14.968

# Files are now in cache
list.files(cache_path)
#> [1] "8cf8e3c0440797a3" "b9ef0ae235fd3194" "f4cad949517a257c"

# Requesting the same data should be faster because it should load from cache.
# But it seems this only happens if `memoised = TRUE` in subsequent calls?
system.time(dat <- getDataset("GSE46416"))
#>    user  system elapsed 
#>   0.501   0.096   7.702
system.time(dat <- getDataset("GSE46416"))
#>    user  system elapsed 
#>   0.470   0.085   7.020
system.time(dat <- getDataset("GSE46416", memoised = TRUE))
#>    user  system elapsed 
#>   0.065   0.007   0.072
```

```r
# **Restart R to test between-session caching**

library(gemma.R)

# Cache isn't set on package load.
getOption("gemma.cache")
#> NULL

# So setup the cache again in the same location.
cache_path <- rappdirs::user_cache_dir(appname = "gemmaR")
options(gemma.cache = cache_path)
getOption("gemma.cache")
#> [1] "~/Library/Caches/gemmaR"

# The files are still in the cache.
list.files(cache_path)
#> [1] "8cf8e3c0440797a3" "b9ef0ae235fd3194" "f4cad949517a257c"

# Requesting the same data should be faster because it should load from cache.
# But it seems this only happens if `memoised = TRUE` in subsequent calls?
system.time(dat <- getDataset("GSE46416"))
#>    user  system elapsed 
#>   6.290   0.426  14.522
system.time(dat <- getDataset("GSE46416", memoised = TRUE))
#>    user  system elapsed 
#>   0.086   0.009   0.096
```

```r
# **Restart R and turn off internet connection*.*

library(gemma.R)

# Cache isn't set on package load.
getOption("gemma.cache")
#> NULL

# So setup the cache again in the same location.
cache_path <- rappdirs::user_cache_dir(appname = "gemmaR")
options(gemma.cache = cache_path)
getOption("gemma.cache")
#> [1] "~/Library/Caches/gemmaR"

# The files are still in the cache.
list.files(cache_path)
#> [1] "8cf8e3c0440797a3" "b9ef0ae235fd3194" "f4cad949517a257c"

# The data are not loaded from the cache (unless `memoised = TRUE`)
system.time(dat <- getDataset("GSE46416"))
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: gemma.msl.ubc.ca
#> Timing stopped at: 0.052 0.013 0.081
system.time(dat <- getDataset("GSE46416", memoised = TRUE))
#>    user  system elapsed 
#>    6.26    0.39    6.89
```

* [x]  The top-level files `examples.txt`, `registry.R`, and `registry_helpers.R` are non-standard files, so you will need to justify their inclusion in the git repo. Tagging @Bioconductor/core for their input.
> these files were moved to `inst/script` as suggested by @lshep
* [x]  Upon acceptance, please update installation instructions in the `README` and vignette (it is recommended to only refer to or emphasise the 'official' Bioconductor installation instructions, to avoid issues with people installing incompatible versions of software when using the 'GitHub' installation instructions).
> the order of installation instructions have been flipped to make the bioconductor version the prominent version.

* [x]  Please add a `BugReports` field to the `DESCRIPTION` (typically, this would list https://github.com/PavlidisLab/gemma.R/issues).
> added
* [x]  The `vignettes/se.rds` file should be elsewhere (see https://contributions.bioconductor.org/docs.html?q=vignette#vignettes-directory-and-intermediate-files). Better yet may be to avoid relying on this precomputed result and instead actually evaluate the `dat <- getDataset("GSE46416")` code as part of the vignette (it only takes a few seconds on my system, so I don't think this should cause the package build to exceed time limits). If you have to use precomputed results then please follow the advice in https://contributions.bioconductor.org/data.html, in particular I think your use case is covered by https://contributions.bioconductor.org/data.html?q=data#internal-data.

> saved file and dependency to it removed

* [x]  Please check that the documentation of all function return values (via the roxygen tag `@return`) statements are accurate and sufficient.
  
  * [x]  Several man pages document the return value as `Varies`, which is insufficient. Please describe the various outputs the function may return and why.
  * [x]  What's documented in `@return` is not always accurate. E.g., `getDatasetAnnotations("GSE2018")` returns a _data.table_  not an "array of annotations" ('array' has a specific meaning within R).
  
> documentations now include proper data types when describing what they return.

* [x]  Please document which genomes (and builds) are supported by gene-based functions, such as `getGeneGO()`. I think this is probably documented on the main **gemma** website, but the **gemma.R** package should clearly state this, too.
> The latest date our GO database has been updated was added to the documentation. In the future this will be replaced with a endpoint providing the most up to date version. `getGenomeVersions` function was added to return the current genome versions for the available species. This function currently only returns information for human, mouse and rat genome versions.

* [x]  Why does documentation of `memoised` in `getDataset()` say,  "[SummarizedExperiment] vignette .. the ExpressionSet vignette for more details"? These vignettes don't have anything to do with memoisation.
> this was a mistake and is now fixed

* [ ]  Please provide documentation that describes how the DE analyses are performed  (i.e. the results returned by `getDatasetDE()`). I couldn't find this information in the package or on https://pavlidislab.github.io/Gemma/.

### Recommended
* [ ]  Is it possible to return (or convert) the DE results as/to a standard Bioconductor data structure such as a _MArrayLM_ (from **limma**),
  _DESeqDataSet_ (from **`DESeq2**),  or a _DGELRT_ (from **edgeR**)? My understanding is that the DE results are precomputed and downloaded from the **gemma** service, but if it happened that the code used to generate these relied on these standard Bioconductor tools then perhaps this is feasible? If such conversions were feasible, then **gemma.R** would benefit from the broader Bioconductor ecosystem, e.g.,
  
  * Using `limma::treat()` instead of _ad hoc_ filtering of DE results based on logFC cutoff (see http://bioinformatics.oxfordjournals.org/content/25/6/765 for why the latter is not statistically rigorous).
  * Using `limma::volcanoplot()` or **EnhancedVolcano** instead of re-implementing volcano plots in the vignette.

> it is probably better to implement this as a future update as it will either require a change in the API itself or will require compiling data from multiple endpoints to populate the object

* [x]  In vignette, use `assay(manic, "counts")` rather than `assays(manic)$counts`.
> changed

* [x]   Please take all reasonable steps to address the `NOTES` produced by running `BiocCheck::BiocCheck()` on the package. In particular, I would expect these 2 issues be addressed:
  
  * Avoid using `=` for assignment and use `<-` instead.
  * Consider adding runnable examples to man pages that document exported objects.

> these particular issues have been adressed. all examples are now runnable. (a few longer running functions that are prone to timeout errors will be removed if bioconductor tests fail)

* [x]  What's the difference between `getDatasetDE()` and `getDatasetDEA()`? I couldn't tell from the function names or documentation, but they return very different results (compare `getDatasetDE("GSE2018")` to `getDatasetDEA("GSE2018")`) I _think_ the latter is some sort of summary of the former.
> documentation for these functions are now clarified.

* [ ]  How do the gene-based functions compare to existing ways of using Bioconductor to achieve the same functionality. e.g., Why should a user use `gemma.R::getGeneLocation()` and what pros/cons does this have over more general Bioconductor-based solutions such as https://www.bioconductor.org/packages/release/workflows/vignettes/annotation/inst/doc/Annotation_Resources.html
> these are convenience functions designed to ensure compatibility with Gemma's databases only present to facilitate use

* [x]  Good job with your unit tests. You might take a look at `covr::report()` to get an idea of where coverage might be improved.
> Went through the report and filled in most of the gaps as needed. Note that caching isn't tested for each function since the underlying mechanism is identical between the different functions. Caching code bulked up a bit with the last update causing lower apparent coverage

### CODE REVIEW

**Comment by oganm** [comment]
Fixes
---------

>  The default cache location is rappdirs::user_cache_dir(appname = "gemmaR") (as set by gemma.R:::gemmaCache()) but is documented in the vignette as being tools::R_user_dir("gemmaR", which = "cache"). Please reconcile.

documentation fixed

>  The value of getOption("gemma.cache") is not respected by the caching functionality. I.e. if a user sets this to a non-default location then it is silently ignored; see reprex below.

Using non-default cache locations used to require reloading of the package. This behaviour is now changed so that reloading the package is no longer necessary

**Comment by oganm** [comment]
> Is it possible to return (or convert) the DE results as/to a standard Bioconductor data structure such as a _MArrayLM_ (from **limma**),
  _DESeqDataSet_ (from **`DESeq2**),  or a _DGELRT_ (from **edgeR**)? My understanding is that the DE results are precomputed and downloaded from the **gemma** service, but if it happened that the code used to generate these relied on these standard Bioconductor tools then perhaps this is feasible? If such conversions were feasible, then **gemma.R** would benefit from the broader Bioconductor ecosystem, e.g.,
> 
>   * Using `limma::treat()` instead of _ad hoc_ filtering of DE results based on logFC cutoff (see http://bioinformatics.oxfordjournals.org/content/25/6/765 for why the latter is not statistically rigorous).
>   * Using `limma::volcanoplot()` or **EnhancedVolcano** instead of re-implementing volcano plots in the vignette.

this should be theoretically possible but might need time and work to implement properly.

* are we still using a in house implementation of limma? if we aren't we should be able to expose the R object directly via an endpoint
* otherwise the object documentation is [here](http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/limma/html/lmFit.html) and it can be manually populated. but will likely need to be written as a high level function to grab additional data required

**Comment by oganm** [comment]
>  Please document which genomes (and builds) are supported by gene-based functions, such as getGeneGO(). I think this is probably documented on the main gemma website, but the gemma.R package should clearly state this, too.


gene location endpoint returns the external database hg38. i assume this is is accurate and in sync with the rest of gemma. if so this can be used to return the genome build

https://gemma.msl.ubc.ca/rest/v2/genes/1859/locations

didn't see a "loophole" like that for go though

**Comment by oganm** [comment]
add disclaimers about Go term access

**Comment by oganm** [comment]
note: 

code to look for `=` instead of `<-`

```r
library(dplyr)

file = 'R/validators.R'


data= file %>% readLines() %>% paste(collapse='\n') %>% parse(text = .,keep.source = TRUE) %>% getParseData 

data %>% filter(grepl('ASSIGN',token))

```

**Review by yavyx — COMMENTED** [review]
Hi @oganm,
Is there a specific reason why you removed the `all` parameter in this? Paul and I discussed this quite a bit when I was in the lab and we decided that it was useful to have it, since some datasets have many DE tables and downloading all that data at once by default would not be super useful to the user unless they explicitly want all of it. It also takes quite a while to download all the tables together if there are many.

**Comment by oganm** [comment]
That's me not being privy to earlier discussions but my thinking was that a function should not return different data types without an explicit request.

When `all = TRUE` the code still checked to see what the length of the output was and returned a table or a list based the size of the object instead of being predictable, this could be addressed by just removing that check

But then when `all=FALSE` it simply returned an error with multi study datasets which to me suggested any programmatic use would have to set `all=TRUE` to make sure all results are acquired then would have to deal with outputs of different data types for any downstream analysis.

Will talk to Paul about putting it back

**Comment by yavyx** [comment]
I see what you mean, that makes sense. BTW thank you so much for helping with this, we're almost there.

**Pull request merged**
